my_shop/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('products/', include('simpleapp.urls')),
    path('', include('news.urls')),
    path('news/', include('news.urls')),
    path('accounts/', include('allauth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    # path('', include('allauth.urls')),
]

news/urls.py
from django.urls import path
from . import views
from .views import NewsList, NewsDetail, NewsF , NewsCreate, NewsDelete, NewsUpdate, upgrade_me
from .views import DefaultView, news_by_category, NewsByCategory, follow_category, NewsByAuthor, unfollow_category
 
urlpatterns = [
    # path — означает путь. В данном случае путь ко всем товарам у нас останется пустым, 
    # позже станет ясно почему
    path('', NewsList.as_view(), name='all_news'),
    path('<int:pk>', NewsDetail.as_view(), name='news_detail'),
    path('search', NewsF.as_view(), name='search_news'),
    path('add/', NewsCreate.as_view(), name='add_news'),
    path('<int:pk>/delete/', NewsDelete.as_view(), name='delete_news'),
    path('<int:pk>/edit/', NewsUpdate.as_view(), name='edit_news'),
    path('upgrade/', upgrade_me, name = 'upgrade'),
    path('default/', DefaultView.as_view()),
    path('category/<int:pk>/', NewsByCategory.as_view(), name='news_by_cat'),
    path('category/<int:pk>/follow/', follow_category, name='follow_category'),
    path('category/<int:pk>/unfollow/', unfollow_category, name='unfollow_category'),
    path('author/<int:pk>/', NewsByAuthor.as_view(), name='news_by_author'),
    ]

news/models.py
from tabnanny import verbose
from django.db import models as m
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse_lazy


# Create your models here.

class Author(m.Model):
    user = m.OneToOneField(User, on_delete=m.CASCADE)
    rating = m.SmallIntegerField(default=0, verbose_name='Рейтинг')

    def update_rating(self):
        post_rating_sum = self.post_set.all().aggregate(post_rating=Sum('rating'))
        comment_rating_sum = self.user.comment_set.all().aggregate(comment_rating=Sum('rating'))
        self.rating = post_rating_sum.get('post_rating') * 3 + comment_rating_sum.get('comment_rating')
        self.save()

    def get_absolute_url(self):
        return reverse_lazy('news_by_author', kwargs = {'pk':self.id})

    def __str__(self) -> str:
        name = f"{self.user.last_name} {self.user.first_name}".strip()
        name = '<anonymous author>' if not name else name
        return name

    
class Category(m.Model):
    name = m.CharField(max_length=30, unique=True, verbose_name="Категория")
    user = m.ManyToManyField(User, through='UserCategory')

    def get_absolute_url(self):
        return reverse_lazy('news_by_cat', kwargs = {'pk':self.id})

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ['-name']
        verbose_name = "Категория"
        verbose_name_plural = 'Категории'

class UserCategory(m.Model):
    category = m.ForeignKey(Category, on_delete=m.CASCADE)
    user = m.ForeignKey(User, on_delete=m.CASCADE)

    class Meta:
        constraints = [
            m.UniqueConstraint('user_id', 'category_id', name='unique_user_category')
        ]

class Post(m.Model):
    NEWS = 'NWS'
    ARTICLE = 'ACL'
    TYPES = [
        (NEWS, 'новость'),
        (ARTICLE, 'статья')
    ]
    author = m.ForeignKey(Author, on_delete=m.CASCADE, verbose_name="Автор")
    type = m.CharField(max_length=3, choices=TYPES, verbose_name="Тип")
    created_dtm = m.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    title = m.CharField(max_length=255, verbose_name='Заголовок')
    content = m.TextField(verbose_name='Текст')
    categories = m.ManyToManyField(Category, through='PostCategory')
    rating = m.SmallIntegerField(default=0, verbose_name='Рейтинг')

    def __str__(self) -> str:
        return f"{self.title=}, {self.type=}"

    def preview(self):
        return self.content[:124] + '...'

    def like(self):
        self.rating += 1

    def dislike(self):
        self.rating -= 1

    def get_absolute_url(self): # добавим абсолютный путь, 
        #чтобы после создания нас перебрасывало на страницу с товаром
        return reverse_lazy('news_detail', kwargs = {'pk':self.id})

    class Meta:
        ordering = ['-created_dtm']

class PostCategory(m.Model):
    post = m.ForeignKey(Post, on_delete=m.CASCADE)
    category = m.ForeignKey(Category, on_delete=m.CASCADE)

    class Meta:
        constraints = [
            m.UniqueConstraint('post_id', 'category_id', name='unique_post_category')
        ]


class Comment(m.Model):
    post = m.ForeignKey(Post, on_delete=m.CASCADE)
    user = m.ForeignKey(User, on_delete=m.CASCADE)
    text = m.TextField()
    created_dtm = m.DateTimeField(auto_now_add=True)
    rating = m.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1

    def dislike(self):
        self.rating -= 1

    def __str__(self):
        return f"by {self.user.username} at {self.created_dtm.strftime('%Y-%m-%d %H:%M:%S')}"


class PostAuthor(m.Model):
    id = m.BigIntegerField(primary_key=True)
    Название_статьи = m.CharField(max_length=255)
    Дата_создания = m.DateTimeField(auto_now_add=False)
    Имя_пользователя = m.CharField(max_length=50)
    Автор = m.CharField(max_length=40)
    content = m.TextField()

    def save(self, *args, **kwargs):
        raise NotSupportedError('This model is tied to a view, it cannot be saved.')

    class Meta:
        managed = False
        db_table = 'vw_news_filter'
        # verbose_name = 'Example'
        # verbose_name_plural = 'Examples'
        # ordering = ['name']
        

templates/inc/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-lg-top">
    <div class="container">
        <a class="navbar-brand" href="#">Django rules!</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="#">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="/pages/about/">О нас</a></li>
                <li class="nav-item"><a class="nav-link" href="/pages/contact/">Контакты</a></li>
                <li class="nav-item"><a class="nav-link" href="/products/">Товары</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'all_news' %}">Статьи и новости</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'search_news' %}">Статьи и новости: поиск</a></li>
                {% if perms.news.add_post %}
                <li class="nav-item"><a class="nav-link" href="{% url 'add_news' %}">Добавить статью или новость</a></li>
                {% endif %}    

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Подписаться на категории новостей</a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                            {% for cat in user_has_no_categories %}
                            <li><a class="dropdown-item" href="{% url 'follow_category' cat.pk %}">
                                {{ cat.name }}</a>
                            </li>
                            {% empty %}
                            <li class="dropdown-item">Вы подписаны на все категории</li>
                            {% endfor %}
                        </ul>
                </li>    
          
                
                <li class="nav-item"><a class="nav-link" href="/accounts/logout">Выйти</a></li>
            </ul>
        </div>
    </div>
</nav>

templates/inc/_paginator.html
<section name="paginator" class="pagination text-center mt-5 sticky-lg-bottom">
    {% if is_paginated %}
    <nav aria-label="...">
        <ul class="pagination justify-content-end">           
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a href="?page=1"  class="page-link">Первая</a>
                </li>
                <li class="page-item">
                    <a href="?page={{ page_obj.previous_page_number }}"  class="page-link">Предыдущая</a>
                </li>
                <li class="page-item">
                    <a href="?page={{ page_obj.previous_page_number }}"  class="page-link">{{ page_obj.previous_page_number }}</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Предыдущая</a>
                </li>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link">{{ num }}</a>
                </li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %} 
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Следующая</a>
                </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}  
</section>

templates/inc/_sidebar.html
<div class="list-group">
    <h5>Категории:</h5>         
    <div class="col-lt-1">
        {% for cat in categories %} 
        <a href="{{ cat.get_absolute_url }}" class="list-group-item list-group-item-action" aria-current="true">
        {{ cat.name }} <span class="'badge rounded-pill text-bg-primary">{{ cat.cnt }}</span>
        </a>
        {% endfor %}
        <hr>
        <a href="{% url 'all_news' %}" class="list-group-item list-group-item-action" aria-current="true">
            <Все категории> <span class="'badge rounded-pill text-bg-primary"> {{ news_count }}</span>
        </a>
    </div>                         
    <!-- <a href="#" class="btn btn-secondary">Подписаться</a> -->
    
</div> 
<hr>
<h5>Авторы:</h5>
<!-- <div class="row">                            -->
<div class="list-group">
        
    <div class="col-lt-1">
        {% for auth in authors %} 
        <a href="{{ auth.get_absolute_url }}" class="list-group-item list-group-item-action" aria-current="true">
        {{ auth|default:'anonymous' }} <span class="'badge rounded-pill text-bg-primary"> {{ auth.cnt }}</span>
        </a>
        {% endfor %}
        <hr>
        <a href="{% url 'all_news' %}" class="list-group-item list-group-item-action" aria-current="true">
            <Все авторы> <span class="'badge rounded-pill text-bg-primary"> {{ news_count }}</span>
        </a>
    </div>                         
    <!-- <a href="#" class="btn btn-secondary">Подписаться</a> -->
    
</div> 